version: '2'

services:
  web:
    command: npm run dev
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "8080:8080"
    environment:
      - MONGO_DB_URI=mongodb://gerolomo:gerolomo5298@maringa-noticias-shard-00-00-y6ngn.gcp.mongodb.net:27017,maringa-noticias-shard-00-01-y6ngn.gcp.mongodb.net:27017,maringa-noticias-shard-00-02-y6ngn.gcp.mongodb.net:27017/maringa-noticias?ssl=true&replicaSet=maringa-noticias-shard-0&authSource=admin&retryWrites=true&w=majority
